<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <div class="ma-0 pa-0">
        <v-divider class="my-0 pa-0"></v-divider>
        <div class="hb-bab-wrapper d-flex align-center">
            <div class="hb-bab-left-actions-wrapper">
                <!-- please keep both slots, one is to keep old functionality working, the other is the correct name -->
                <slot name="left-actions"></slot>
                <slot name="leftactions"></slot>
                <!-- please keep both slots, one is to keep old functionality working, the other is the correct name -->
            </div>
            <v-spacer></v-spacer>
            <div class="d-flex align-center pr-4 hb-bab-right-actions-wrapper">
                <hb-link v-if="footerCancelOption" :class="{'mr-3' : hasOldActionsSlot}" @click="close">{{closeInsteadOfCancel ? 'Close' : 'Cancel'}}</hb-link>
                
                <span class="hb-bab-right-actions-wrapper-span">
                    <slot name="right-actions"></slot>
                </span>

                <slot name="actions"></slot>
            </div>
        </div>
    </div>
</template>
<script type="text/babel">

    import HbLink from './HbLink.vue';
    
    export default {
        name: "HbBottomActionBar",
        components:{
            HbLink
        },
        computed: {
            hasOldActionsSlot(){
                return !!this.$slots['actions'];
            },
        },
        methods: {
            close(){
                this.$emit('close');
            }
        },
        props: {
            footerCancelOption: {
                type: Boolean,
                default: true
            },
            closeInsteadOfCancel:{
                type: Boolean,
                default: false
            },
        },
    }
</script>

<style scoped>

.hb-bab-wrapper {
    background: linear-gradient(180deg, #FFFFFF 0%, #F9FAFB 100%);
    height: 59px;
    padding-left: 8px;
}

.hb-bab-left-actions-wrapper >>> a:nth-of-type(1) {
    padding-left: 8px;
}

.hb-bab-right-actions-wrapper .hb-bab-right-actions-wrapper-span >>> button, .hb-bab-right-actions-wrapper .hb-bab-right-actions-wrapper-span >>> a {
    margin-left: 12px;
}

</style>