<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <span class="pa-0 ma-0 mb-n2" v-if="to">
        <router-link :id="id" class="hb-breadcrumb-router-link" :to="to">
            <span class="d-flex align-center">
                <hb-icon class="mt-1 mr-1" color="#00848E">mdi-chevron-left</hb-icon> 
                <span class="mt-1 hb-breadcrumb-default-font-size ml-n1">
                    <slot></slot>
                </span>
            </span>
        </router-link>
    </span>
    <span class="pa-0 ma-0 mb-n2" v-else>
        <hb-link :id="id" :href="href" :target="target" @click="$emit('click')" v-bind="$attrs">
            <span class="d-flex align-center">
                <hb-icon class="mt-1 mr-1" color="#00848E">mdi-chevron-left</hb-icon> 
                <span class="mt-1 hb-breadcrumb-default-font-size ml-n1">
                    <slot></slot>
                </span>
            </span>
        </hb-link>
    </span>
</template>
<script type="text/babel">

    import HbLink from './HbLink.vue';
    import HbIcon from './HbIcon.vue';

    export default {
        name: "HbBreadcrumb",
        components: {
            HbLink,
            HbIcon
        },
        props: [ 'to', 'href', 'target', 'id' ],
    }
</script>

<style scoped>

.hb-breadcrumb-default-font-size {
    font-size: 14px;
}

.hb-breadcrumb-router-link {
    color: #00848E;
    text-decoration: none;
}

</style>