<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
  <span>
    start
    <span v-if="icon">
      <v-tooltip bottom :disabled="disabled">
        <template v-slot:activator="{ on }">
          <v-hover v-slot:default="{ hover }">
            <v-btn
              :id="id"
              :to="to"
              :height="height"
              :href="href"
              :target="target"
              medium
              class="hb-v-btn-icon"
              :ripple="false"
              :disabled="disabled"
              icon
              v-on="on"
              :class="{
                'hb-button-icon-hover': hover && !hoverBackgroundColor,
                'hb-button-icon-active': button && !activeBackgroundColor,
              }"
              @click="buttonClicked"
              :style="
                (hoverBackgroundColor && hover) ||
                (activeBackgroundColor && button)
                  ? 'background-color:' + overwriteDefaultColors
                  : ''
              "
            >
              <hb-icon
                :hover="hover"
                :toggle="toggle"
                :small="small"
                :color="color"
                :hover-color="hoverColor"
                :active-color="activeColor"
                :active-state-off="activeStateOff"
                :mdi-icon="mdiIcon"
              >
                <slot></slot>
              </hb-icon>
            </v-btn>
          </v-hover>
        </template>
        <span>{{ tooltip }}</span>
      </v-tooltip>
    </span>
    <span v-else-if="type === 'icon' && !icon">
      <v-tooltip bottom :disabled="disabled">
        <template v-slot:activator="{ on }">
          <v-hover v-slot:default="{ hover }">
            <v-btn
              :id="id"
              :to="to"
              :href="href"
              :target="target"
              medium
              class="hb-v-btn-icon"
              :ripple="false"
              :disabled="disabled"
              icon
              v-on="on"
              :class="{
                'hb-button-icon-hover': hover && !hoverBackgroundColor,
                'hb-button-icon-active': button && !activeBackgroundColor,
              }"
              @click="buttonClicked"
              :style="
                (hoverBackgroundColor && hover) ||
                (activeBackgroundColor && button)
                  ? 'background-color:' + overwriteDefaultColors
                  : ''
              "
            >
              <slot :hover="hover" :toggle="toggle"></slot>
            </v-btn>
          </v-hover>
        </template>
        <span>{{ tooltip }}</span>
      </v-tooltip>
    </span>
    <span v-else>
      <v-hover v-slot:default="{ hover }">
        <v-btn
          :id="id"
          :to="to"
          :href="href"
          :target="target"
          :small="sizeSmall"
          :loading="loading"
          :large="sizeLarge"
          :block="block"
          :min-width="minWidth"
          :class="[buttonClass, hover ? hoverClass : '']"
          depressed
          :ripple="false"
          :disabled="disabled"
          @click="$emit('click')"
        >
          <v-icon
            left
            v-if="prependIcon"
            :size="small ? '16' : large ? '24' : '20'"
            :color="color === 'secondary' ? '#637381' : '#FFFFFF'"
            :class="small ? 'mr-1' : 'mr-2'"
            >{{ prependIcon }}</v-icon
          >
          <span :class="[textSize, textColor]" class="font-weight-regular">
            <slot></slot>
          </span>
          <v-icon
            right
            v-if="appendIcon"
            :size="small ? '16' : large ? '24' : '20'"
            :color="color === 'secondary' ? '#101318' : '#FFFFFF'"
            :class="small ? 'ml-0' : 'ml-1'"
            >{{ appendIcon }}</v-icon
          >
        </v-btn>
      </v-hover>
    </span>
    finish
  </span>
</template>
<script type="text/babel">
import HbIcon from "./HbIcon.vue";

export default {
  name: "HbButton",
  data: function () {
    return {
      toggle: false,
    };
  },
  components: {
    HbIcon,
  },
  created() {
    if (this.activeByDefault) {
      this.toggle = true;
    }
    if (this.active) {
      this.toggle = true;
    }
  },
  computed: {
    buttonClass() {
      if (this.color === "primary") {
        return "hb-primary-button";
      } else if (this.color === "destructive") {
        return "hb-destructive-button";
      } else if (this.color === "secondary") {
        return "hb-secondary-button";
      } else {
        return "hb-primary-button";
      }
    },
    hoverClass() {
      if (this.color === "primary") {
        return "hb-primary-button-hover";
      } else if (this.color === "destructive") {
        return "hb-destructive-button-hover";
      } else if (this.color === "secondary") {
        return "hb-secondary-button-hover";
      } else {
        return "";
      }
    },
    sizeSmall() {
      if (this.small) {
        return true;
      } else {
        return false;
      }
    },
    sizeLarge() {
      if (this.large) {
        return true;
      } else {
        return false;
      }
    },
    textSize() {
      if (this.small) {
        return "hb-button-text-small";
      } else if (this.large) {
        return "hb-button-text-large";
      } else {
        return "hb-button-text-regular";
      }
    },
    textColor() {
      if (this.color === "secondary") {
        return "hb-btn-black-text";
      } else {
        return "hb-btn-white-text";
      }
    },
    button() {
      if (this.active === true) {
        return true;
      }
      if (this.activeStateOff === true) {
        return false;
      } else {
        return this.toggle;
      }
    },
    overwriteDefaultColors() {
      if (this.activeBackgroundColor && this.button) {
        return this.activeBackgroundColor;
      } else if (this.hoverBackgroundColor) {
        return this.hoverBackgroundColor;
      } else {
        return "";
      }
    },
  },
  methods: {
    buttonClicked() {
      this.toggle = !this.toggle;
      this.$emit("click");
    },
  },
  watch: {
    active() {
      this.toggle = this.active;
    },
  },
  props: {
    type: {
      type: String,
    },
    icon: {
      type: Boolean,
      default: false,
    },
    color: {
      type: String,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    small: {
      type: Boolean,
      default: false,
    },
    large: {
      type: Boolean,
      default: false,
    },
    prependIcon: {
      type: String,
    },
    appendIcon: {
      type: String,
    },
    tooltip: {
      type: String,
    },
    activeByDefault: {
      type: Boolean,
      default: false,
    },
    activeStateOff: {
      type: Boolean,
      default: false,
    },
    hoverBackgroundColor: {
      type: String,
    },
    activeBackgroundColor: {
      type: String,
    },
    active: {
      type: Boolean,
      default: false,
    },
    block: {
      type: Boolean,
      default: false,
    },
    to: {
      type: String,
    },
    href: {
      type: String,
    },
    target: {
      type: String,
    },
    activeColor: {
      type: String,
    },
    hoverColor: {
      type: String,
    },
    loading: {
      type: Boolean,
      default: false,
    },
    minWidth: {
      type: String,
      default: "0",
    },
    height: {
      type: Number,
      default: 40,
    },
    id: {
      type: String,
    },
    mdiIcon: {
      type: String,
    },
  },
};
</script>

<style scoped>
.hb-btn-black-text {
  color: #101318;
}

.hb-btn-white-text {
  color: #ffffff;
}

.v-btn {
  letter-spacing: normal;
}
.v-btn::before {
  background: inherit;
}
.hb-opacity-50 {
  opacity: 0.5;
}
.hb-button-text-small {
  font-size: 12px;
}
.hb-button-text-regular {
  font-size: 14px;
}
.hb-button-text-large {
  font-size: 16px;
}
.hb-primary-button {
  background: linear-gradient(180deg, #47c0bf -70%, #00848e 126.25%);
  border: 1px solid #00848e;
  box-shadow: 0px 1px 0px rgba(22, 29, 37, 0.05);
  color: #ffffff;
}
.hb-primary-button-hover {
  background: linear-gradient(180deg, #47c0bf -142.5%, #00848e 103.75%);
  border: 1px solid #005f66;
}
.hb-secondary-button {
  background: linear-gradient(180deg, #ffffff 0%, #f9fafb 100%);
  border: 1px solid #c4cdd5;
  box-shadow: 0px 1px 0px rgba(22, 29, 37, 0.05);
}
.hb-secondary-button-hover {
  background: linear-gradient(180deg, #fafbfc 0%, #ebeff2 100%);
}
.hb-full-width-button {
  background: #ffffff !important;
  border: 1px solid #c4cdd5;
  box-shadow: 0px 1px 0px rgba(22, 29, 37, 0.05);
}
.hb-destructive-button {
  background: linear-gradient(180deg, #d34b30 -70%, #c24228 126.25%);
  border: 1px solid #a13621;
  box-shadow: 0px 1px 0px rgba(22, 29, 37, 0.05);
  color: #ffffff;
}
.hb-destructive-button-hover {
  background: linear-gradient(180deg, #d34b30 -133.75%, #c24228 106.25%);
  border: 1px solid #8c2f1d;
}

.v-tooltip {
  position: relative;
  z-index: 99999;
}
.v-tooltip__content {
  background: #334450 !important;
  opacity: 1 !important;
}

.v-btn.hb-button-icon-hover {
  background: #dfe3e8;
}
.v-btn.hb-button-icon-active {
  background: #e0f5f5;
}
.v-btn > .v-btn__content .v-icon {
  color: #637381;
}
.v-btn.v-btn--disabled svg:not(.svg-outlier) path {
  fill: #cecece;
}
.v-btn.v-btn--disabled svg.svg-outlier path {
  stroke: #cecece;
}
.hb-user-avatar {
  font-size: 18px;
}
.hb-v-btn-icon.v-btn--icon.v-size--default {
  height: 40px;
  width: 40px;
}
</style>
