<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-card
        v-bind="$attrs"
        v-on="$listeners"
        class="hb-card-wrapper"
        :elevation="elevation"
    >
        <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>

        <v-row no-gutters class="px-4 hb-card-title d-flex align-center" v-if="!noTitle">
            <span v-if="title && !hasTitleSlot">
                {{ title }}
            </span>
            <slot name="title"></slot>
        </v-row>
        
        <v-divider v-if="!noTitle"></v-divider>

        <slot></slot>
    </v-card>
</template>

<script type="text/babel">

export default {
    name:'HbCard',
    data(){
        return {

        }
    },
    computed: {
        hasTitleSlot(){
            return !!this.$slots['title'];
        },
    },
    props: {
        elevation: {
            default: '1'
        },
        title: {
            type: String,
            default: undefined
        },
        noTitle: {
            type: Boolean,
            default: false
        }
    }
}
</script>

<style scoped>

.hb-card-title {
    font-size: 16px;
    line-height: 24px;
    font-weight: 500;
    min-height: 52px;
}

</style>