<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-checkbox
        v-model="vmodel"
        class="hb-aviary-v-checkbox"
        v-bind="$attrs"
        v-on="$listeners"
        color="#00848E"
    >
        <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]><slot :name="slot"/></template>
    </v-checkbox>
</template>

<script type="text/babel">

export default {
    name:'HbCheckbox',
    data(){
        return {

        }
    },
    computed: {
        vmodel: {
            get () {
                return this.$attrs.value
            },
            set (value) {
                this.$emit('input', value)
            }
        }
    },
}
</script>

<style>

.hb-aviary-v-checkbox.v-input--selection-controls:not(.v-input--is-label-active) i.v-icon, .hb-aviary-v-checkbox.v-input--selection-controls.v-input--is-disabled:not(.v-input--is-label-active) i.v-icon {
  color: #DFE3E8 !important;
}

.hb-aviary-v-checkbox.v-input--selection-controls:not(.v-input--is-label-active):hover i.v-icon, .hb-aviary-v-checkbox.v-input--selection-controls.v-input--is-disabled:not(.v-input--is-label-active):hover i.v-icon {
  color: #637381 !important;
}

.hb-aviary-v-checkbox.v-input--selection-controls.v-input--is-disabled i.v-icon, .hb-aviary-v-checkbox.v-input--selection-controls.v-input--is-disabled label {
    opacity: .35 !important;
}

.hb-aviary-v-checkbox .v-label {
    color: #101318 !important;
    font-size: 14px !important;
}

</style>