<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <span class="hb-combobox">
        <v-select
            v-if="select"
            offset-y
            v-model="combobox"
            multiple
            small-chips
            class="hb-combobox pt-0"
            v-bind="$attrs"
            v-on="$listeners"
            :menu-props="{
                contentClass: 'hb-combobox-menu',
                offsetY: true,
            }"
            single-line
            hide-details
            :clearable="true"
            @click:clear="$emit('input', [])"
            clear-icon="mdi-close-circle"
        >
            <template v-slot:prepend-item>
                <v-list-item
                    @click="toggle"
                    v-if="$attrs && $attrs.items && $attrs.items.length > 1"
                >
                    <v-list-item-action>
                        <hb-icon :color="$attrs.value.length === 0 ? '#DFE3E8' : '#00848E'">{{ icon }}</hb-icon>
                    </v-list-item-action>
                    <v-list-item-content>
                        <v-list-item-title>Select All</v-list-item-title>
                    </v-list-item-content>
                </v-list-item>
            </template>
            <template v-slot:selection="{ item, parent }">
                <hb-combobox-chip @click="parent.selectItem(item)">
                    <template v-if="item.name">{{ item.name }}</template>
                    <template v-else>{{ item }}</template>
                </hb-combobox-chip>
            </template>
            <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]><slot :name="slot"/></template>
        </v-select>
        <v-combobox
            v-else
            v-model="combobox"
            multiple
            small-chips
            class="hb-combobox pt-0"
            v-bind="$attrs"
            v-on="$listeners"
            :menu-props="{ contentClass: 'hb-combobox-menu' }"
            single-line
            hide-details
            :clearable="true"
            @click:clear="$emit('input', [])"
            clear-icon="mdi-close-circle"
            @update:search-input="updateInput"
        >
            <template v-slot:prepend-item>
                <v-list-item
                    @click="toggle"
                    v-if="$attrs && $attrs.items && $attrs.items.length > 1 && !inputValue"
                >
                    <v-list-item-action>
                        <hb-icon :color="$attrs.value.length === 0 ? '#DFE3E8' : '#00848E'">{{ icon }}</hb-icon>
                    </v-list-item-action>
                    <v-list-item-content>
                        <v-list-item-title>Select All</v-list-item-title>
                    </v-list-item-content>
                </v-list-item>
            </template>
            <template v-slot:selection="{ item, parent }">
                <hb-combobox-chip @click="parent.selectItem(item)" v-if="(item && item.name && item.name.length) || (item && item.length) ">
                    <template v-if="item.name">{{ item.name }}</template>
                    <template v-else>{{ item }}</template>
                </hb-combobox-chip>
            </template>
            <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]><slot :name="slot"/></template>
        </v-combobox>

    </span>
</template>

<script type="text/babel">

import HbIcon from './HbIcon.vue';
import HbComboboxChip from './HbComboboxChip.vue';

export default {
    name:'HbCombobox',
    data(){
        return {
            inputValue: null,
        }
    },
    components:{
        HbIcon,
        HbComboboxChip
    },
    computed: {
        combobox: {
            get () {
                return this.$attrs.value
            },
            set (value) {
                this.$emit('input', value)
            }
        },
        allSelected() {
            return this.$attrs.items.every(elem => this.$attrs.value.includes(elem));
        },
        icon() {
            if (this.$attrs.value.length === 0) return 'mdi-checkbox-blank-outline';
            if (this.allSelected) return 'check_box';
            if (!this.allSelected) return 'mdi-minus-box';
            return 'mdi-checkbox-blank-outline';
        },
    },
    props: {
        select:{
            type: Boolean,
            default: false
        },
    },
    methods: {
        toggle() {
            this.$nextTick(() => {
                if(this.allSelected) {
                    this.$emit('input', []);
                } else {
                    this.$emit('input', this.$attrs.items.slice());
                }
            })
        },
        updateInput(value){
            this.inputValue = value;
        }
    },
    watch: {
        combobox (val, prev) {
            if (val.length === prev.length) return

            this.combobox = val.map(v => {
                if (v.length > 0 && this.$attrs.items.indexOf(v) === -1) {
                    this.$attrs.items.push(v)
                }

                return v
            })
        },
    }
}
</script>

<style scoped>

.hb-combobox .hb-form-description-text-night-light {
    color: #637381;
}

.hb-combobox .hb-combobox-primary-color {
    color: #00848E;
}

.hb-combobox >>> .v-select__slot {
    margin-bottom: 4px !important;
}

.hb-combobox-menu >>> i.v-icon.notranslate.material-icons.theme--light {
  color: #DFE3E8 !important;
}

.v-input.hb-combobox:not(.v-input--is-dirty) {
    margin-top: -6px;
}

.v-input.hb-combobox.v-input--is-dirty {
    margin-top: .5px;
}

</style>

<style>

.v-menu__content.hb-combobox-menu .v-select-list {
    margin-top: 1px;
}

.v-menu__content.hb-combobox-menu .v-select-list .v-list-item--link::before {
    background: transparent !important;
}

.v-menu__content.hb-combobox-menu .v-select-list .v-list-item--link:hover::before {
    background: rgba(0, 0, 0, 0.87) !important;
}

.v-menu__content.hb-combobox-menu .v-select-list .v-list-item__title {
    font-size: 14px;
    color: #101318;
}

.v-menu__content.hb-combobox-menu .v-select-list .v-list-item__action {
    margin-right: 7px;
}

.v-menu__content.hb-combobox-menu .v-list-item:not(.v-list-item--active) .v-simple-checkbox .v-icon {
  color: #DFE3E8 !important;
}

.v-menu__content.hb-combobox-menu .v-icon.primary--text {
    color: #00848E !important;
}

</style>