<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-chip
        color="#00848E"
        outlined
        class="hb-combobox-chip ml-0 mr-2 mb-1"
        :class="{'mt-1 mr-2 hb-combobox-chip-cursor-pointer' : display}"
        small
        style="max-width: 480px;"
    >
        <span class="hb-combobox-chip-overflow">
            <slot></slot>
        </span>
        <hb-icon
            small
            color="#00848E"
            @click="$emit('click')"
            class="hb-combobox-chip-close hb-combobox-chip-cursor-pointer"
            v-if="!display"
        >
            mdi-close-circle
        </hb-icon>
    </v-chip>
</template>

<script type="text/babel">

import HbIcon from './HbIcon.vue';

export default {
    name:'HbComboboxChip',
    data(){
        return {

        }
    },
    components:{
        HbIcon
    },
    props: {
        display:{
            type: Boolean,
            default: false
        },
    }
}
</script>

<style scoped>

.hb-combobox-chip.v-chip.v-size--small {
    padding: 0 7px 1px 7px;
}

.hb-combobox-chip.v-chip.v-chip--outlined.v-chip.v-chip, .hb-combobox-chip.v-chip.v-chip--outlined.v-chip.v-chip:hover::before {
    background-color: #ffffff !important;
}

.hb-combobox-chip .hb-combobox-chip-close {
    margin-bottom: 2px;
    margin-left: 7px;
    margin-right: -1px;
}

.hb-combobox-chip-cursor-pointer {
    cursor: pointer;
}

.hb-combobox-chip .hb-combobox-chip-overflow {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

</style>