<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <div>
        <v-row class="my-3 mx-0 d-flex align-center">
            <v-col :cols="leftColumns" class="ma-0 pa-0 hb-data-table-text-light">
                <slot name="description"></slot>
            </v-col>
            <v-spacer></v-spacer>
            <v-col :cols="rightColumns" class="ma-0 pa-0 text-right">
                <slot name="actions"></slot>
            </v-col>
        </v-row>
    </div>
</template>

<script type="text/babel">

export default {
    name:'HbDataTableHeader',
    data(){
        return {

        }
    },
    props: {
        leftColumns:{
            type: String,
            default: '9'
        },
        rightColumns:{
            type: String,
            default: '3'
        },
    }
}
</script>

<style scoped>

    .hb-data-table-text-light {
        color: #637381;
        font-size: 14px;
        line-height: 24px;
    }

</style>