<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <div>
        <v-card elevation="1" v-if="card">
            <v-data-table
                class="hb-data-table-wrapper"
                v-bind="$attrs"
                v-on="$listeners"
                :disable-pagination="disablePagination"
                :hide-default-footer="hideDefaultFooter"
            >
                <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>
            </v-data-table>
        </v-card>
        <v-data-table
            v-else
            class="hb-data-table-wrapper"
            v-bind="$attrs"
            v-on="$listeners"
            :disable-pagination="disablePagination"
            :hide-default-footer="hideDefaultFooter"
        >
            <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>
        </v-data-table>
    </div>
</template>

<script type="text/babel">

export default {
    name:'HbDataTable',
    data(){
        return {

        }
    },
    props: {
        card: {
            type: Boolean,
            default: true
        },
        disablePagination: {
            type: Boolean,
            default: true
        },
        hideDefaultFooter: {
            type: Boolean,
            default: true
        }
    }
}
</script>

<style>

    .hb-data-table-wrapper.v-data-table table thead {
        background-color: #F4F6F8;
    }
    .hb-data-table-wrapper.v-data-table table thead tr th {
        color: #474F5A !important;
        font-weight: 500;
        font-size: 12px !important;
    }
    .hb-data-table-wrapper.v-data-table table thead tr th:hover {
        color: #101318 !important;
    }
    .hb-data-table-wrapper.v-data-table td {
        font-size: 12px !important;
        line-height: 16px !important;
    }
    .hb-data-table-wrapper.v-data-table tbody tr {
        cursor: pointer;
    }
    .hb-data-table-wrapper.v-data-table tbody tr:hover {
        background: #eeeeee !important;
    }

</style>