<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-expansion-panel
        class="hb-expansion-panel-wrapper mt-0"
        :class="[extraClassBorder, !noTopMargin ? 'mt-4' : '']"
        v-bind="$attrs"
        v-on="$listeners"
    >
        <v-expansion-panel-header class="px-4" :class="extraClass" :expand-icon="expandIconOff ? '' : 'mdi-chevron-down'">
          <v-row class="ma-0 pa-0">
            <v-col class="pa-0 ma-0 d-flex align-center">
                <hb-icon class="mr-2" v-if="titleIconCheck" :color="titleIconColorCheck">{{ titleIconCheck }}</hb-icon>
                <span class="hb-expansion-panel-title-font-size font-weight-medium hb-expansion-panel-default-font-color">
                  <slot name="title"></slot>
                </span>
            </v-col>
            <v-spacer v-if="hasActionsSlot"></v-spacer>
            <v-col v-if="hasActionsSlot" class="pa-0 ma-0 d-flex align-center justify-end">
                <slot name="actions"></slot>
            </v-col>
          </v-row>
        </v-expansion-panel-header>
        <v-divider></v-divider>
        <v-expansion-panel-content class="hb-expansion-panel-content-wrapper pa-0 ma-0" elevation="0">
            <slot name="content"></slot>
        </v-expansion-panel-content>
    </v-expansion-panel>
</template>

<script type="text/babel">

import HbIcon from './HbIcon.vue';

export default {
    name:'HbExpansionPanel',
    data(){
        return {

        }
    },
    components: {
      HbIcon,
    },
    computed: {
      hasActionsSlot(){
        return !!this.$slots['actions'];
      },
      extraClass(){
        if(this.error){
          return 'hb-expansion-panel-error';
        } else if(this.caution){
          return 'hb-expansion-panel-caution'
        } else if(this.success){
          return 'hb-expansion-panel-success'
        } else {
          return 'hb-expansion-panel-default'
        }
      },
      extraClassBorder(){
        if(this.error){
          return 'hb-expansion-panel-error-border';
        } else if(this.caution){
          return 'hb-expansion-panel-caution-border'
        } else if(this.success){
          return 'hb-expansion-panel-success-border'
        } else {
          return 'hb-expansion-panel-default-border'
        }
      },
      titleIconCheck(){
        if(this.titleIcon){
          return this.titleIcon;
        } else if(this.error){
          return 'mdi-alert';
        } else if(this.caution){
          return 'mdi-alert'
        } else if(this.success){
          return 'mdi-check'
        } else {
          return false
        }
      },
      titleIconColorCheck(){
        if(this.titleIconColor){
          return this.titleIconColor;
        } else if(this.error){
          return '#FB4C4C';
        } else if(this.caution){
          return '#FFD600';
        } else if(this.success){
          return '#02AD0F';
        } else {
          return '#101318';
        }
      }
    },
    props: {
      error: {
        type: Boolean,
        default: false
      },
      caution: {
        type: Boolean,
        default: false
      },
      success: {
        type: Boolean,
        default: false
      },
      titleIcon: {
        type: String,
        default: undefined
      },
      titleIconColor: {
        type: String,
        default: undefined
      },
      noTopMargin: {
        type: Boolean,
        default: false
      },
      expandIconOff: {
        type: Boolean,
        default: false
      }
    }
}
</script>

<style scoped>

.hb-expansion-panel-wrapper.v-expansion-panel {
  border-radius: 4px !important;
  min-height: 52px;
}

.hb-expansion-panel-wrapper.v-expansion-panel > .v-expansion-panel-header {
  min-height: 52px;
}

.hb-expansion-panel-wrapper .v-expansion-panel-header .v-expansion-panel-header__icon .v-icon {
    color: #637381;
}

.hb-expansion-panel-wrapper .v-expansion-panel-header {
  padding: 2px 0;
}

.hb-expansion-panel-wrapper .v-expansion-panel-header.hb-subpanel-header {
  min-height: 38px;
}

.hb-expansion-panel-wrapper .v-input label {
  margin-top: -2px;
}

.hb-expansion-panel-wrapper .v-expansion-panel-header {
  border-radius: 0 !important;
}

.hb-expansion-panel-wrapper:not(:first-child)::after {
  border-top: none !important;
}

.hb-expansion-panel-default-font-color {
    color: #101318;
}

.hb-expansion-panel-default-font-size {
    font-size: 14px;
}

.hb-expansion-panel-title-font-size {
    font-size: 16px;
}

.hb-custom-switch-label {
  min-width: 30px;
}

.hb-expansion-panel-error {
  background-color: #F8E5E1;
}

.hb-expansion-panel-caution {
  background-color: #FFF9DA;
}

.hb-expansion-panel-success {
  background-color: #E1FAE3;
}

.hb-expansion-panel-error-border {
  border: 1px solid #f96060;
}

.hb-expansion-panel-caution-border {
  border: 1px solid #FFD600;
}

.hb-expansion-panel-success-border {
  border: 1px solid #72d479;
}

</style>

<style>

.hb-expansion-panel-wrapper .hb-expansion-panel-content-wrapper .v-expansion-panel-content__wrap {
  padding: 0;
  margin: 0;
}

</style>