<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-card class="ma-0 pa-0 d-flex align-stretch" flat color="transparent">
        <div>
            <v-avatar
                tile
                size="48"
            >
                <svg v-if="contact" width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <circle cx="24" cy="24" r="23.3947" fill="white" stroke="#DFE3E8" stroke-width="1.21053"/>
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M28.6793 19.3208C28.6793 21.906 26.5854 24 24.0001 24C21.4148 24 19.3208 21.906 19.3208 19.3208C19.3208 16.7355 21.4148 14.6415 24.0001 14.6415C26.5854 14.6415 28.6793 16.7355 28.6793 19.3208ZM14.6416 31.0189C14.6416 27.9072 20.8767 26.3396 24.0001 26.3396C27.1235 26.3396 33.3586 27.9072 33.3586 31.0189V33.3585H14.6416V31.0189Z" fill="#637381"/>
                </svg>

                <hb-unit-icon v-if="unit && (unit.type || unit.unit_type)" :unit="unit"></hb-unit-icon>

            </v-avatar>
        </div>
        <div
            class="pl-6 hb-header-info-wrapper hb-header-info-text-light hb-header-info-default-font-size"
        >
            <span v-if="contact">
                <v-row class="d-flex align-center" :style="maxWidthIsSet ? 'max-width:' + rowMaxWidth : ''">
                    <span class="hb-header-info-title font-weight-medium text-capitalize mr-1">
                        {{ contact.salutation }} {{ contact.first }} {{ contact.middle }} {{ contact.last }} {{ contact.suffix }}
                    </span>
                    <span v-if="contact.Military && contact.Military.active" class="mt-2 mx-1">
                        <hb-tooltip>
                            <template v-slot:item>
                                <hb-icon small color="#101318">mdi-custom-active-military</hb-icon>
                            </template>
                            <template v-slot:body>
                                Active Military
                            </template>
                        </hb-tooltip>
                    </span>
                    <hb-status v-if="!statusOff && status" :status="status" class="ml-1 mt-1">{{ status }}</hb-status>
                </v-row>
                <v-row :style="maxWidthIsSet ? 'max-width:' + rowMaxWidth : ''" class="hb-header-info-default-font-size">
                    <span v-if="contact.Phones && contact.Phones[0] && contact.Phones[0].phone_verified && contact.Phones[0].phone_verified === 1" class="hb-verified-icon-margin-fix"><hb-icon small color="success">mdi-account-check</hb-icon></span>
                    <span v-if="contact.Phones && contact.Phones[0] && $props.smsClick"><hb-link color="secondary" @click="$emit('smsClicked')">{{ contact.Phones[0].phone | formatPhoneHeaderInfo }}</hb-link></span>
                    <span v-else-if="contact.Phones && contact.Phones[0]">{{ contact.Phones[0].phone | formatPhoneHeaderInfo }}</span>
                    <span v-if="(contact.Phones && contact.Phones[0]) && (contact.email && contact.email.length)" class="mx-1">|</span>
                    <span v-if="contact.email && contact.email.length && !disableEmail" class="d-flex align-center">
                        <span v-if="contact.email_verified && contact.email_verified === 1" class="hb-verified-icon-margin-fix"><hb-icon small color="success">mdi-account-check</hb-icon></span>
                        <hb-link color="secondary" @click="$emit('emailClicked')">{{ contact.email }}</hb-link>
                    </span>
                    <span v-if="((contact.Phones && contact.Phones[0]) || (contact.email && contact.email.length)) && ((contact.Addresses && contact.Addresses[0]) || (access && access.length))" class="mx-1">|</span>
                    <span v-if="contact.Addresses && contact.Addresses[0]">{{contact.Addresses[0].Address.address}}<span v-if="contact.Addresses[0].Address.address2" class="ml-1">{{contact.Addresses[0].Address.address2}}</span>, {{contact.Addresses[0].Address.city}} {{contact.Addresses[0].Address.zip}}</span>
                    <span v-if="((contact.Phones && contact.Phones[0]) || (contact.email && contact.email.length) || contact.Addresses && contact.Addresses[0]) && access && access.length > 0" class="mx-1">|</span>
                    <span v-if="access && access.length === 1 && !disableCode">Access Code: <hb-link @click="$emit('pin')">{{access[0] && access[0].pin ? access[0].pin : 'Not Set'}}</hb-link></span>
                    <span v-else-if="access && access.length === 1">Access Code: {{access[0] && access[0].pin ? access[0].pin : 'Not Set'}}</span>
                    <span v-if="access && access.length > 1 && !disableCode"><hb-link @click="$emit('pin')">Multiple Access Codes</hb-link></span>
                    <span v-else-if="access && access.length > 1">Multiple Access Codes</span>
                </v-row>
            </span>
            <span v-if="unit">
                <v-row class="d-flex align-center" :style="maxWidthIsSet ? 'max-width:' + rowMaxWidth : ''">
                    <span class="hb-header-info-title font-weight-medium mr-1">Space {{unit.number}}</span>
                    <span v-if="insurance && insurance.id" class="mt-n1 mx-1">
                        <hb-tooltip>
                            <template v-slot:item>
                                <hb-icon small color="#101318">mdi-security</hb-icon>
                            </template>
                            <template v-slot:body>
                                {{insurance.name}}<br />
                                {{insurance.description}}
                            </template>
                        </hb-tooltip>
                    </span>
                    <hb-status v-if="!statusOff && status" :status="status" class="ml-1 mt-1">{{ status }}</hb-status>
                </v-row>
                <v-row :style="maxWidthIsSet ? 'max-width:' + rowMaxWidth : ''" class="hb-header-info-default-font-size">
                    <span v-if="unit.label" class="mr-1">{{unit.label}} |</span><span v-if="unit.Category && unit.Category.name">{{ unit.Category.name }}</span><span v-if="unit.Category && unit.Category.name && (unit.property_number || unit.Address.city)" class="mx-1">|</span>{{unit.property_number}}<span v-if="unit.property_number && unit.Address.city" class="mx-1">-</span><span v-if="unit.Address && unit.Address.city">{{unit.Address.city}}</span>
                </v-row>
            </span>
        </div>
    </v-card>
</template>
<script type="text/babel">

    import HbUnitIcon from './HbUnitIcon.vue';
    import HbIcon from './HbIcon.vue';
    import HbLink from './HbLink.vue';
    import HbStatus from './HbStatus.vue';
    import HbTooltip from './HbTooltip.vue';

    import { parsePhoneNumber } from 'libphonenumber-js';

    export default {
        name: "HbHeaderInfo",
        computed: {
            status(){
                if(this.statusIs){
                    return this.statusIs;
                }
                else if(this.contact && this.contact.status) {
                    return this.contact.status;
                }
                else if(this.unit && this.unit.status) {
                    return this.unit.state;
                }
                else {
                    return false;
                }
            },
            maxWidthIsSet(){
                if(this.rowMaxWidth){
                    return true;
                } else {
                    return false;
                }
            }
        },
        components:{
            HbUnitIcon,
            HbIcon,
            HbLink,
            HbStatus,
            HbTooltip
        },
        props: [ 'contact', 'unit', 'statusIs', 'statusOff', 'rowMaxWidth', 'insurance', 'access', 'disableEmail', 'disableCode', 'smsClick' ],
        filters:{
            formatPhoneHeaderInfo(value){
                if (!value) return '';
                    try {
                        var parsedPhoneNumber = parsePhoneNumber('+' + value);

                        if(parsedPhoneNumber && parsedPhoneNumber.isValid()){
                            if(parsedPhoneNumber.country === 'US'){
                                return '+1 ' + parsedPhoneNumber.formatNational();
                            } else {
                                return parsedPhoneNumber.formatInternational();
                            }
                        } else {
                            value = value.toString();

                            var numbers = value.replace(/\D/g, ''), char = {0: '(', 3: ') ', 6: '-'};
                            value = '';
                            for (var i = 0; i < numbers.length; i++) {
                                value += (char[i] || '') + numbers[i];
                            }
                        }
                    }   catch(err){
                    }
                return value;
            }
        },
    }
</script>

<style scoped>

.break-word {
    word-break: break-word;
}

.hb-header-info-text-light {
    color: #637381;
}

.hb-header-info-default-font-size {
    font-size: 14px;
    line-height: 22px;
    font-weight: normal;
}

.hb-header-info-title {
    color: #101318;
    font-size: 24px;
    line-height: 22px;
}

.hb-verified-icon-margin-fix {
    margin-top: -2px;
    margin-right: 3px;
}

</style>