<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <span v-if="to">
        <router-link :id="id" :class="linkClass" :to="to">
            <slot></slot>
        </router-link>
    </span>
    <span v-else>
        <a :id="id" :class="linkClass" :href="href" :target="target" @click.stop="$emit('click')">
            <slot></slot>
        </a>
    </span>
</template>
<script type="text/babel">

    export default {
        name: "HbLink",
        computed: {
            linkClass(){
                if(this.color === 'primary'){
                    return 'hb-link';
                }
                else if(this.color === 'secondary'){
                    return 'hb-link-secondary';
                }
                else if(this.color === 'tertiary'){
                    return 'hb-link-tertiary';
                }
                else if(this.color === 'destructive'){
                    return 'hb-text-destroy-status';
                }
                else {
                    return 'hb-link';
                }
            }
        },
        props: {
            to: {
                type: String,
                default: undefined
            },
            href: {
                type: String,
                default: undefined
            },
            target: {
                type: String,
                default: undefined
            },
            color: {
                type: String,
                default: undefined
            },
            id: {
                type: String,
                default: undefined
            }
        }
    }
</script>

<style scoped>

.v-application a.hb-link-secondary, .hb-link-secondary {
  color: #306FB6;
  text-decoration:none;
}
.v-application a.hb-link-tertiary, .hb-link-tertiary {
  color: #637381;
  text-decoration:none;
}
.v-application a.hb-link-night, .hb-link-night {
  color: #101318;
  text-decoration:none;
}
.v-application a.hb-text-destroy-status, .hb-text-destroy-status {
  color: #FB4C4C;
  text-decoration:none;
}
.v-application a.hb-link-disabled, .hb-link-disabled {
  color: #919EAB;
  text-decoration:none;
  cursor:default;
}
.v-application a.hb-link, .hb-link {
  color: #00848E;
  text-decoration:none;
}

</style>