<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-menu
        :close-on-click="closeOnClick"
        :close-on-content-click="closeOnContentClick"
        :offset-y="offsetY"
        content-class="hb-menu-options-wrapper"
        v-bind="$attrs"
        v-on="$listeners"
        >
        <template v-slot:activator="{ on, attrs }">
            <span v-bind="attrs" v-on="on" class="d-flex">
                <hb-btn icon tooltip="More Options" active-state-off v-if="options">
                    mdi-dots-vertical
                </hb-btn>
                <span v-else class="d-flex">
                    <slot name="menu-activator"></slot>
                </span>
            </span>
        </template>
        <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]><slot :name="slot"/></template>
    </v-menu>
</template>

<script type="text/babel">

import HbButton from './HbButton.vue';

export default {
    name:'HbMenu',
    data(){
        return {

        }
    },
    components: {
        HbButton
    },
    computed: {
        vmodel: {
            get () {
                return this.$attrs.value
            },
            set (value) {
                this.$emit('input', value)
            }
        }
    },
    props: {
        closeOnClick:{
            type: Boolean,
            default: true
        },
        closeOnContentClick:{
            type: Boolean,
            default: true
        },
        offsetY:{
            type: Boolean,
            default: true
        },
        options:{
            type: Boolean,
            default: false
        }
    }
}
</script>

<style>

.hb-menu-options-wrapper .v-list-item, .hb-menu-options-wrapper .v-list-item__title {
    font-size: 14px;
}

.hb-menu-options-wrapper .v-list {
    padding-top: 0;
    padding-bottom: 0;
}

</style>