<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-dialog
        v-model="dialog"
        :width="dialogSize"
        :fullscreen="fullscreen"
        :persistent="persistent"
        :scrollable="scrollable"
        slot="body"
        :content-class="confirmation ? 'hb-modal-wrapper hb-delete-border' : 'hb-modal-wrapper'"
    >
        <template v-slot:activator="{ on, attrs }">
            <span v-bind="attrs" v-on="on">
                <slot name="activator"></slot>
            </span>
        </template>

        <v-card>
            <v-card-title class="hb-modal-title d-flex align-center ma-0 pa-0" :class="{'hb-modal-caution' : confirmation}">
                <v-col :cols="hasHeaderSlot ? 3 : 10" class="ma-0 py-0 px-4 d-flex align-start">
                    <slot name="icon" v-if="hasIconSlot"></slot>
                    <hb-icon v-if="confirmation && !hasIconSlot" class="pr-2" :class="{ 'mt-n1' : icon === 'mdi-alert-circle-outline' }" color="#101318">{{ icon }}</hb-icon>
                    <span class="hb-modal-title-font-size">{{ title }}</span>
                </v-col>
                <v-col :cols="hasHeaderSlot ? 9 : 2" class="ma-0 pa-0 hb-modal-header-close-padding-right d-flex justify-end">
                    <slot name="header"></slot>
                    <hb-btn icon tooltip="Close" @click="close" active-state-off :hover-background-color="confirmation ? '#F5EBB7' : ''">mdi-close</hb-btn>
                </v-col>
            </v-card-title>
            <v-divider></v-divider>
            <v-card-text class="pa-0 ma-0">
                <div>
                    <span v-if="hasSubheaderSlot && size !== 'small' && !noSubHeader">
                        <div class="hb-modal-sub-header px-4">
                            <slot name="subheader"></slot>
                        </div>
                        <v-divider></v-divider>
                    </span>
                    <span class="hb-modal-content">
                        <slot name="content"></slot>
                    </span>
                </div>
            </v-card-text>
            <hb-bottom-action-bar v-if="!footerOff" :footerCancelOption="footerCancelOption" :closeInsteadOfCancel="closeInsteadOfCancel" @close="close">

                <template v-slot:left-actions>
                    <slot name="left-actions"></slot>
                </template>
                <template v-slot:leftactions>
                    <slot name="leftactions"></slot>
                </template>

                <template v-slot:right-actions>
                    <slot name="right-actions"></slot>
                </template>
                <template v-slot:actions>
                    <slot name="actions"></slot>
                </template>

            </hb-bottom-action-bar>
        </v-card>
    </v-dialog>
</template>
<script type="text/babel">

    import HbIcon from './HbIcon.vue';
    import HbButton from './HbButton.vue';
    import HbLink from './HbLink.vue';
    import HbBottomActionBar from './HbBottomActionBar.vue';
    
    export default {
        name: "HbModal",
        components:{
            HbIcon,
            HbButton,
            HbLink,
            HbBottomActionBar
        },
        computed: {
            dialog: {
                get () {
                    return this.value
                },
                set (value) {
                    this.$emit('input', value)
                }
            },
            hasHeaderSlot(){
                return !!this.$slots['header'];
            },
            hasIconSlot(){
                return !!this.$slots['icon'];
            },
            fullscreen(){
                if(this.size === 'fullscreen'){
                    return true;
                } else {
                    return false;
                }
            },
            dialogSize(){
                if(this.size === 'small'){
                    return '360';
                }
                else if(this.size === 'medium'){
                    return '480';
                }
                else if(this.size === 'large'){
                    return '720';
                }
                else {
                    return '720';
                }
            },
            hasSubheaderSlot(){
                return !!this.$slots['subheader'];
            },
            hasHeaderLeftSlot(){
                return !!this.$slots['header-left'];
            },
            /* not necessary
            displayFooterCancelOption() {
                return !!this.footerCancelOption;
            },
            */
            icon(){
                if(this.titleIcon){
                    return this.titleIcon;
                } else {
                    return 'mdi-alert-circle-outline';
                }
            }
        },
        methods: {
            close(){
                this.$emit('close');
                setTimeout(() => {
                    this.dialog = false;
                }, 200);
            }
        },
        props: {
            size:{
                type: String
            },
            title:{
                type: String
            },
            titleIcon:{
                type: String
            },
            persistent:{
                type: Boolean,
                default: true
            },
            value:{
                type: Boolean,
                default: false
            },
            footerOff:{
                type: Boolean,
                default: false
            },
            scrollable:{
                type: Boolean,
                default: true
            },
            footerCancelOption: {
                type: Boolean,
                default: true
            },
            closeInsteadOfCancel:{
                type: Boolean,
                default: false
            },
            confirmation: {
                type: Boolean,
                default: false
            },
            noSubHeader: {
                type: Boolean,
                default: false
            }
        },
    }
</script>

<style scoped>

.hb-modal-fullscreen-footer {
  position: fixed;
  border-top: 1px solid #DFE3E8;
  bottom: 0;
  width: 100%;
}

.hb-modal-sub-header {
  min-height: 44px;
  padding-top: 11px;
  padding-bottom: 14px;
  font-size: 14px;
  color: #637381
}

.hb-modal-content {
    font-size: 14px;
    color: #101318;
}

.hb-delete-border {
  border: 2px solid #FFD600;
  border-radius: 6px !important;
}

.hb-modal-caution {
  background-color: #FFF9DA;
}

.hb-modal-header-close-padding-right {
  padding-right: 8px !important;
}

.hb-modal-content .v-input .v-label {
  line-height: 20px;
}

.hb-modal-title-font-size {
    font-size: 16px;
    line-height: 24px;
    font-weight: 500;
}

.hb-modal-title {
    min-height: 52px;
}

.v-card__actions.hb-modal-footer-wrapper {
    background: linear-gradient(180deg, #FFFFFF 0%, #F9FAFB 100%);
    height: 60px;
    padding-left: 8px;
}

</style>

<style>

.v-dialog.hb-modal-wrapper.hb-delete-border {
  border: 2px solid #FFD600;
  border-radius: 6px;
}

</style>