<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <div :class="{'pb-2' : $vuetify.breakpoint.smAndDown}">
        <v-row class="hb-header-font-size font-weight-medium ma-0 pa-0">
            {{ title ? title : ''}}
            <slot name="title"></slot>
        </v-row>
        <v-row class="ma-0 pa-0">
            {{ description ? description : ''}}
            <slot name="description"></slot>
        </v-row>
    </div>
</template>
<script type="text/babel">

    export default {
        name: "HbPageHeader",
        props: [ 'title', 'description' ],
    }
</script>

<style scoped>

.hb-header-font-size{
  font-size: 28px;
  line-height: 32px;
  font-weight: 500;
  letter-spacing: normal;
}

</style>