<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-radio
        class="hb-aviary-v-radio"
        v-bind="$attrs"
        v-on="$listeners"
        color="#00848E"
    >
        <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]><slot :name="slot"/></template>
    </v-radio>
</template>

<script type="text/babel">

export default {
    name:'HbRadio',
    data(){
        return {

        }
    },
}
</script>

<style>

.hb-aviary-v-radio:not(.v-item--active) .v-input--selection-controls__input i.v-icon {
    color: #DFE3E8 !important;
}

.hb-aviary-v-radio:not(.v-item--active) .v-input--selection-controls__input:hover i.v-icon {
    color: #637381 !important;
}

.hb-aviary-v-radio.v-item--active.v-radio--is-disabled i.v-icon {
    color: #00848E !important;
}

.hb-aviary-v-radio.v-radio--is-disabled {
    opacity: .35 !important;
}

.hb-aviary-v-radio .v-label {
    color: #101318 !important;
    font-size: 14px !important;
}

</style>