<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-stepper
        v-model="vmodel"
        class="hb-stepper-wrapper"
        elevation="0"
        :alt-labels="altLabels"
        v-bind="$attrs"
    >
        <slot></slot>
    </v-stepper>
</template>

<script type="text/babel">

export default {
    name:'HbStepper',
    data(){
        return {

        }
    },
    computed: {
        vmodel: {
            get () {
                return this.$attrs.value
            },
            set (value) {
                this.$emit('input', value)
            }
        },
        /*
        stepperClass() {
            switch(this.dividerSpacing){
                case '0':
                    return 'new-tenant-stepper'
                    break;
                case '1':
                    return 'new-tenant-stepper-1'
                    break;
                case '2':
                    return 'new-tenant-stepper-2'
                    break;
                case '3':
                    return 'new-tenant-stepper-3'
                    break;
                case '4':
                    return 'new-tenant-stepper-4'
                    break;
                case '5':
                    return 'new-tenant-stepper-5'
                    break;
                case '6':
                    return 'new-tenant-stepper-5'
                    break;
            }
        }
        */
    },
    props: {
        altLabels:{
            type: Boolean,
            default: true
        },
        dividerSpacing: {
            type: String,
            default: '3'
        }
    }
}
</script>

<style>

.theme--light.v-stepper .v-stepper__step:not(.v-stepper__step--complete):not(.v-stepper__step--error) .v-stepper__step__step {
border: 1px solid #e0e3e7;
background-color: white !important;
color: white;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step .v-stepper__step__step,
.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step {
font-size: 14px;
}


.hb-stepper-wrapper .v-stepper__label {
color: #637381 !important;
text-shadow: none !important;
text-align: center !important;
font-weight: normal !important;
}

.hb-stepper-wrapper .v-stepper__step.v-stepper__step--active .v-stepper__label, .v-stepper__step.v-stepper__step--complete .v-stepper__label{
color: #00848E !important;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__step--active:not(.v-stepper__step--error) .v-stepper__step__step {
border: 1px solid #00848E;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__step--active.v-stepper__step--error .v-stepper__step__step {
background-color: #FB4C4C  !important;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__step--active:not(.v-stepper__step--error) .v-stepper__step__step:before {
content: "";
background: #00848E;
border-radius: 50%;
width: 8px;
height: 8px;
margin: 0 auto;
display: block;
position: absolute;
}

.theme--light.v-stepper.hb-stepper-wrapper {
box-shadow: none !important;
cursor: pointer;
}

.hb-stepper-wrapper .v-stepper__header .v-divider {
margin: 35px 0px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper.new-tenant-stepper-1.v-stepper--alt-labels .v-stepper__header .v-divider {
margin: 35px -20px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper.new-tenant-stepper-2.v-stepper--alt-labels .v-stepper__header .v-divider {
margin: 35px -40px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper.new-tenant-stepper-3.v-stepper--alt-labels .v-stepper__header .v-divider {
margin: 35px -60px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper.new-tenant-stepper-4.v-stepper--alt-labels .v-stepper__header .v-divider {
margin: 35px -80px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper.new-tenant-stepper-5.v-stepper--alt-labels .v-stepper__header .v-divider {
margin: 35px -100px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper.new-tenant-stepper-6.v-stepper--alt-labels .v-stepper__header .v-divider {
margin: 35px -10px 0 !important;
border: 1px solid #e0e3e7;
}

.hb-stepper-wrapper .hb-divider-border-color-success {
border: 1px solid #00848E !important;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__step--error .v-stepper__step__step {
color: white;
border: 2px solid #FB4C4C;
background: #FB4C4C;

}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__inactive .v-stepper__step__step {
border: 2px solid #DFE3E8;
background-color: white !important;
color: white;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__label,
.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__editable .v-stepper__label,
.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__active .v-stepper__label{
color: rgba(0, 0, 0, 0.87);
}


.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__step--error:not(.v-stepper__step--inactive) .v-stepper__label {
color: #00848E !important;
}

.theme--light.v-stepper.hb-stepper-wrapper .v-stepper__step.v-stepper__inactive .v-stepper__label {
color: #DFE3E8;
}

.hb-stepper-wrapper.v-stepper--alt-labels .v-stepper__step {
-ms-flex-preferred-size: 100px;
flex-basis: 100px;
}

.v-stepper__step {
    max-width: 50px;
}

</style>