<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-switch
        v-model="vmodel"
        class="hb-aviary-v-switch"
        v-bind="$attrs"
        v-on="$listeners"
        color="#00848E"
    >
        <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]><slot :name="slot"/></template>
    </v-switch>
</template>

<script type="text/babel">

export default {
    name:'HbSwitch',
    data(){
        return {

        }
    },
    computed: {
        vmodel: {
            get () {
                return this.$attrs.value
            },
            set (value) {
                this.$emit('input', value)
            }
        }
    },
}
</script>

<style>
.hb-aviary-v-switch:not(.v-input--is-label-active) .v-input--switch__thumb {
    background-color: #637381 !important;
}

.hb-aviary-v-switch:not(.v-input--is-label-active) .v-input--switch__track {
    background-color: #c9ced2 !important;
}

.hb-aviary-v-switch.v-input--is-disabled {
    opacity: .35 !important;
}

.hb-aviary-v-switch .v-label {
    color: #101318 !important;
    font-size: 14px !important;
}

</style>