<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<!-- PLEASE DO NOT EDIT THIS FILE -->
<template>
    <v-tabs
        :background-color="backgroundColor"
        class="hb-tabs-wrapper"
        :color="color"
        v-model="vmodel"
        v-bind="$attrs"
        v-on="$listeners"
        :show-arrows="showArrows"
        :slider-color="sliderColor"
    >
        <slot></slot>
    </v-tabs>
</template>

<script type="text/babel">

export default {
    name:'HbTabs',
    data(){
        return {

        }
    },
    computed: {
        vmodel: {
            get () {
                return this.$attrs.value
            },
            set (value) {
                this.$emit('input', value)
            }
        }
    },
    props: {
        backgroundColor: {
            type: String,
            default: '#F9FAFB'
        },
        showArrows: {
            type: Boolean,
            default: true
        },
        sliderColor: {
            type: String,
            default: '#00848E'
        },
        color: {
            type: String,
            default: '#101318'
        }
    }
}
</script>

<style scoped>

.hb-tabs-wrapper {
    color: #637381;
}

.hb-tabs-wrapper >>> .v-tab, .hb-tabs-wrapper >>> a.v-tab {
    text-transform: capitalize !important;
    letter-spacing: normal !important;
    font-size: 14px !important;
    font-weight: normal !important;
}

.hb-tabs-wrapper .v-slide-group__wrapper {
  border-bottom-width: 1px !important;
}

.theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab:not(.v-tab--active), .theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab:not(.v-tab--active) > .v-icon, .theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab:not(.v-tab--active) > .v-btn, .theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab--disabled {
  color: #637381 !important;
}
.theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab:not(.v-tab--active):hover, .theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab:not(.v-tab--active) > .v-icon:hover, .theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab:not(.v-tab--active) > .v-btn:hover, .theme--light.hb-tabs-wrapper.v-tabs > .v-tabs-bar .v-tab--disabled:hover {
  color: #101318 !important;
  background-color: #F9FAFB;
}
.hb-tabs-wrapper >>> .v-tab--active, .hb-tabs-wrapper >>> a.v-tab--active {
  font-weight: 500 !important;
}

</style>